// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjrjuwgdamxufhcsjexb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqcmp1d2dkYW14dWZoY3NqZXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTU3ODcsImV4cCI6MjA2MTk3MTc4N30.4Bg-V1Fr9T4VUGFBsuWL6_CbSJqnS2C9for5Too8h-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);